CREATE TABLE IF NOT EXISTS clients
(
    client_id INTEGER PRIMARY KEY,
    name      VARCHAR(200) NOT NULL,
    email     VARCHAR(254) NOT NULL,
    phone     VARCHAR(50)  NOT NULL
);
CREATE SEQUENCE SEQ_CLIENT START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS products
(
    product_id   INTEGER PRIMARY KEY,
    product_name VARCHAR(200)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    price        VARCHAR(50)   NOT NULL

);
CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;