CREATE TABLE IF NOT EXISTS сlients
(
id INTEGER PRIMARY KEY ,
name VARCHAR(200) NOT NULL ,
email VARCHAR(254) NOT NULL ,
phone VARCHAR(50) NOT NULL
);
/*CREATE SEQUENCE clients_id_seq START WITH 3 INCREMENT BY 1*/
CREATE TABLE IF NOT EXISTS goods(
    id INTEGER PRIMARY KEY ,
    product_name VARCHAR(200) NOT NULL ,
    description VARCHAR(1000) NOT NULL ,
    price VARCHAR(50) NOT NULL

);
